// src/pages/insert-services.jsx

export const TOUS_LES_SERVICES = [
    { id: 1, nom: "Menuiserie", icon: "🪑" },
    { id: 2, nom: "Plomberie", icon: "🚰" },
    { id: 3, nom: "Électricité", icon: "⚡" },
    { id: 4, nom: "Transport", icon: "🚗" },
    { id: 5, nom: "Sécurité", icon: "🛡️" },
    { id: 6, nom: "Ménage", icon: "🧹" },
    { id: 7, nom: "Jardinage", icon: "🌳" },
    { id: 8, nom: "Peinture", icon: "🎨" },
    { id: 9, nom: "Climatisation", icon: "❄️" },
    { id: 10, nom: "Maçonnerie", icon: "🧱" },
    { id: 11, nom: "Serrurerie", icon: "🔑" },
    { id: 12, nom: "Déménagement", icon: "📦" },
    { id: 13, nom: "Couture", icon: "🧵" },
    { id: 14, nom: "Informatique", icon: "💻" },
    { id: 15, nom: "Réparation TV", icon: "📺" },
    { id: 16, nom: "Coiffure", icon: "💇" },
    { id: 17, nom: "Esthétique", icon: "💄" },
    { id: 18, nom: "Blanchisserie", icon: "🧺" },
    { id: 19, nom: "Mécanique Auto", icon: "🔧" },
    { id: 20, nom: "Plâtrerie", icon: "🏗️" },
    { id: 21, nom: "Vitrerie", icon: "🪟" },
    { id: 22, nom: "Chauffage", icon: "🔥" },
    { id: 23, nom: "Décoration", icon: "🖼️" },
    { id: 24, nom: "Piscine", icon: "🏊" },
    { id: 25, nom: "Nettoyage vitre", icon: "🧼" },
    { id: 26, nom: "Cordonnerie", icon: "👞" },
    { id: 27, nom: "Cours particuliers", icon: "📚" },
    { id: 28, nom: "Traduction", icon: "🌐" },
    { id: 29, nom: "Livraison", icon: "🚚" },
    { id: 30, nom: "Restauration", icon: "🍳" },
    { id: 31, nom: "Photographie", icon: "📷" },
    { id: 32, nom: "Vidéo", icon: "🎥" },
    { id: 33, nom: "Graphisme", icon: "🖌️" },
    { id: 34, nom: "Comptabilité", icon: "📊" },
    { id: 35, nom: "Secrétariat", icon: "📑" },
    { id: 36, nom: "Conseil juridique", icon: "⚖️" },
    { id: 37, nom: "Garde d'enfants", icon: "👶" },
    { id: 38, nom: "Garde animaux", icon: "🐾" },
    { id: 39, nom: "Massage", icon: "💆" }
];